### DISCUSSION TITLE
Using with EVCC works if the car is awake but fail to start charging.

### DISCUSSION THREAD

**Discussion by dglaude** [tesla-local-control/tesla_ble_mqtt_docker#48] [Q&A]
I have some experience with evcc, but very few success, and tesla_ble_mqtt is actually really my last hope (please find below most of my failure with other project).

Most of my knowledge and attempt are based on success stories from this discussion: https://github.com/evcc-io/evcc/discussions/14252

So I installed tesla-ble-mqtt-docker on a dedicated Pi4 as close as possible to the car. I made the key installation and played a bit with HA (still confuse about the UI, but my plan is not to use HA much).

Observed what message HA was sending to MQTT (with MQTT Explorer add-on) and configure evcc to use the same trick.

This works fine if I manually start the charge with Tesla android app, at that point evcc can control the amps and follow the sun. But if the car is sleeping, evcc+tesla_ble_mqtt fail to wake up the car and start the charge. I see 5 failed attempt at starting the charge.
At that point evcc is not trying anymore (even if it notice on the Tesla Wall Charger that no electricity is send to the car).

This can happen in the morning when the sun start producing enough, or it can occurs during the day if the charging is stopped (like for cloud or house other consumption of electricity).

One working scenario is when we plug the car and there is enough sun... in that case the Tesla is still awake and start charging automatically, from that point evcc take control of the charge level.

I have a hard time to find the right lines in the log file, because there is no time stamp, and the color full logs are ugly when saved to text.

I am wondering if other have the same problem... and if the wakeup of the car is supposed to be requested by evcc, or is it something tesla_ble_mqtt can do if it fail 5 times to send a "start charge" command.

I can share my current config if it helps, here is the vehicles part:
```
vehicles:
- name: my_car           # reference to standard vehicle
  title: Tesla_Model_Y   # Will be displayed in the user interface (optional)
  type: custom
  capacity: 60
### tesla_ble_mqtt for max current and charge stop/start
  chargeenable:
    source: mqtt
    topic: tesla_ble/XP7YXXXX0XX000000/charging
    payload: '{{if .chargeenable}}start{{else}}stop{{end}}'
  maxcurrent: # set charger max current (A)
    source: mqtt
    topic: tesla_ble/XP7YXXXX0XX000000/charging-set-amps
    payload: '{{.maxcurrent}}'
  wakeup: # vehicle wake up command
    source: mqtt
    topic: tesla_ble/XP7YXXXX0XX000000/command
    payload: 'wake'
### Teslamate for SoC, range and status
  soc:
    source: mqtt
    topic: teslamate/cars/1/battery_level
    timeout: 8h
  range:
    source: mqtt
    topic: teslamate/cars/1/est_battery_range_km
    timeout: 8h
  status:
    source: combined
    plugged:
      source: mqtt
      topic: teslamate/cars/1/plugged_in
      timeout: 8h
    charging:
      source: mqtt
      topic: teslamate/cars/1/charging_state
      timeout: 8h
```

Any success or similar failure report would help me, any documentation on how to do it would help to. I can document my solution, but it is a bit of a mess... it use teslamate for soc information and I have a real Tesla Wall Connector (that seems dump).

Anyone with a documentation of how they did it... I could check for typo or ideas... else I might need to document completely what I did.

PS... my failure list:
1) Plain simple evcc with tesla template (require support of evcc) => that worked for a few hours until I reached the API limit.
2) Using evcc and https://github.com/wimaha/TeslaBleHttpProxy with custom car template => that is randomly working, sometimes for 24H or 48H then fail for unknown reason, and sometime rework after a restart or long wait. I tested on two separates Pi4 and an Intel NUC
3) Using script that call https://github.com/teslamotors/vehicle-command on an Intel NUC, this worked fine but from time to time the BLE interface (hci0) disapear and sometimes reapear as hci1. That is maybe an hardware issue with BLE on the NUC, restart usually fix it (but not always).
