### ISSUE TITLE
0.22 vs 0.4x vs Tesla Fleet vs HA 2025.x

### ISSUE THREAD

**Issue by dettofatto** [tesla-local-control/tesla_ble_mqtt_docker#78]
Hello, thank you for your magnificent work, as you might have noticed, I’m a fan of yours! I’ve attached a screenshot to show you how I’m using your Docker, which I’m currently running on version 0.22. I wanted to ask if these observations can also be applied to the newer versions.
I’m using Tesla Fleet at the same time as your tool, where Tesla Fleet is used for querying data, and your tool is used for sending commands. The Docker runs on a Raspberry Pi 4 located near the cars, and the execution time for a command is about 7 seconds. I have solar panels, and my goal is to regulate the charging process based on the sunlight.

As you can see, I’m charging two Tesla cars. The first one is on a three-phase connection (max 11kW), and the other on a single-phase connection (max 3.5kW). I’ve added numbers (in yellow) on the screenshot for reference:

Line 1 corresponds to the kW reserved for my house (I can choose manually), which is calculated as a ratio of solar production and the value read by an automation that adjusts the amperage for the two cars. In this case, I’m reserving 0.5kW for the house, the solar production is 4.63kW, and the Tesla value (number 7 in yellow) tells the automation to use 7A for (number 2 in yellow: “Tesla Mia Amperage”), which is triggered by the automation at point 8.
The other Tesla (number 4) is not using automation, and I’ve manually set it to 3A.
If the Tesla value (number 7) increases or decreases, depending on numbers 9 and 1, the amperage (number 2) also increases or decreases.
Furthermore, if I disable 8 and 5, I can manually adjust the amperage on line 2.

After this long introduction, I’ve noticed that with the newer versions, there seems to be command congestion. Often, when both Teslas are no longer at home, I need to restart the Docker, which doesn’t happen with version 0.22.

Additionally, I’ve noticed that with version 0.22, the value at point 6 in yellow on the screenshot isn’t static but instead updates dynamically. Let me explain better:
When I send the command through your Docker (e.g., 7A), the amperage slider in version 0.22 adjusts to 7. However, in version 0.4x, it needs to be updated manually.

On cloudy days, in addition to creating a constant back-and-forth of commands from the automation (which always needs to know the current charging amperage), this results in the "not-at-home" issue. With Tesla Fleet, I don’t experience this problem, and I could continue using TF along with version 0.22, but I’ve noticed that when upgrading to the new version of HA (2025.x), Tesla Fleet becomes almost unusable.

And so, here’s my final question:
Is it possible to somehow integrate or limit Tesla Fleet (which will likely be discontinued soon) and modify your project to follow a similar approach? I’m also attaching my automation.

Thank you for your support and continuous work.

![screenshot ricarica](https://github.com/user-attachments/assets/6bb404b9-cbdc-4e06-9d0a-9470991b3b7d)

Automation (3), I've another automation for 4
```
alias: Ricarica Tesla Mia
description: Aumenta gli ampere di ricarica di Tesla Mia in base alla produzione di energia
triggers:
  - trigger: time_pattern
    seconds: /15
    enabled: true
  - entity_id: sensor.tesla_kw_sottratti_da_casa
    trigger: state
    enabled: true
conditions:
  - condition: device
    device_id: 930976fa5e779b9b4646ef6e4c82da50
    domain: lock
    entity_id: 01e8c773262645fc62a3a483651c08d6
    type: is_locked
  - condition: state
    entity_id: sensor.tesla_mia_charging
    state: charging
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: -10000
            below: 0.6
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: sensor.tesla_mia_charger_current
                below: 2.1
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 0
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 0.6
            below: 1.32
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 2.1
                above: 1.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 2
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 1.32
            below: 1.99
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: sensor.tesla_mia_charger_current
                below: 3.1
                above: 2.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 3
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 1.99
            below: 2.64
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 4.1
                above: 3.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 4
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 2.64
            below: 3.3
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 5.1
                above: 4.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 5
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 3.3
            below: 3.96
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 6.1
                above: 5.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 6
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 3.96
            below: 4.6
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 7.1
                above: 6.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 7
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 4.5
            below: 5.28
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 8.1
                above: 7.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 8
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 5.28
            below: 5.94
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 9.1
                above: 8.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 9
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 5.94
            below: 6.6
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 10.1
                above: 9.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 10
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 6.6
            below: 7
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 13.1
                above: 12.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 13
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 7
            below: 7.2
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 15.1
                above: 14.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 15
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tesla_kw_sottratti_da_casa
            above: 7.2
            below: 12
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: number.tesla_mia_charge_current
                below: 16.1
                above: 15.9
        sequence:
          - device_id: fd6deb800e11e84cd1f19c4ad77860ba
            domain: number
            entity_id: 59cc05d8fa2aedf960c9c67fb0f2c041
            type: set_value
            value: 16
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
          - data:
              entity_id:
                - number.tesla_mia_charge_current
            action: homeassistant.update_entity
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
mode: single
```
