### ISSUE TITLE
Entities do not update after command

### ISSUE THREAD

**Issue by epenet** [tesla-local-control/tesla_ble_mqtt_docker#82]
Hi,

I recently updated to use v0.3.0, and I was surprised to find out that the "charging_current" and "charger" entities are no longer updated after a successful command.

Previously, I think it worked in "optimistic" mode => HA would keep the value that was sent to `tesla-local-control`, even if the command failed.
Now, it seems to work in "pessimistic" mode => HA keeps the last values retrieved by "force data update" button, even if the command succeeded.

This caused my solar-automations to fail, and now I have to keep track of a new entity just to keep track of the last charging current sent to `tesla-local-control`.

I would suggest that all controls entities (number and switch) also send a state update if the command was successful.

**Comment by iainbullock** [comment]
It was my intention that the state_topic is updated either by polling or by pressing the "force data update" button. This is how it is done in https://github.com/alandtse/tesla

On my HA automations, whenever there is a command sent, I call a script which delays for 15 secs then 'presses' the relevant force update button. The script is also in 'restart' mode which means if it gets called before completion, it restarts which prevents multiple consecutive calls (which is bad for the bluetooth). Here's an example:
```
alias: EV Delay Force Update Charge
sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.tesla_ble_lrw3f7XXXXXX3_force_update_charge
description: ""
mode: restart
icon: mdi:database-refresh
```

However both the OP and @dettofatto have found this breaks existing automations. 

I could implement one or both of the following selectable options:

 1 - An environment variable to turn off MQTT optimistic mode. Your HA entities will be immediately set by HA when changed in HA. This will not necessarily be same as the true state if the bluetooth command failed. The state would be updated on the next polling occurence or when the "force data update" button is pressed

2 - An environment variable set by the user which causes the code to automatically request a state update after a command has been sent. This more than doubles the load on the bluetooth system, which may be a problem for some hardware if automations want to send lots of commands 

Let me know what you think. 

I will update when I get chance (I'm on holiday at the moment so might take me a few days to do it as and when I can)
